In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("Sample - Superstore.xls")

In [3]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2019-103800,2019-01-03,2019-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2019-141817,2019-01-05,2019-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2022-115427,2022-12-30,2023-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2022-156720,2022-12-30,2023-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2022-143500,2022-12-30,2023-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [4]:
managers = pd.read_excel("Sample - Superstore.xls",sheet_name=1)
managers

    Regional Manager   Region
0    Sadie Pawthorne     West
1        Chuck Magee     East
2  Roxanne Rodriguez  Central
3        Fred Suzuki    South

In [5]:
returns = pd.read_excel("Sample - Superstore.xls",sheet_name=2)
returns

    Returned        Order ID
0        Yes  US-2019-100762
1        Yes  US-2019-100762
2        Yes  US-2019-100762
3        Yes  US-2019-100762
4        Yes  US-2019-100867
..       ...             ...
795      Yes  US-2022-147886
796      Yes  US-2022-147998
797      Yes  US-2022-151127
798      Yes  US-2022-155999
799      Yes  US-2022-155999

[800 rows x 2 columns]

In [6]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [7]:
df.shape

(10194, 21)

In [8]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2019-103800,2019-01-03,2019-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2019-141817,2019-01-05,2019-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [9]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10189,10190,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2022-115427,2022-12-30,2023-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2022-156720,2022-12-30,2023-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2022-143500,2022-12-30,2023-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [10]:
df['City']

0              Houston
1           Naperville
2           Naperville
3           Naperville
4         Philadelphia
             ...
10189    New York City
10190        Fairfield
10191         Loveland
10192    New York City
10193    Charlottetown
Name: City, Length: 10194, dtype: object

In [11]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [12]:
product_details = ['Product ID','Category','Sub-Category','Product Name']
df[product_details]

,Product ID,Category,Sub-Category,Product Name
0,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form..."
1,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs
2,OFF-LA-10003223,Office Supplies,Labels,Avery 508
3,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving
4,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...
...,...,...,...,...
10189,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders
10190,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers
10191,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands
10192,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset
10193,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders

In [13]:
df[product_details].head()

,Product ID,Category,Sub-Category,Product Name
0,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form..."
1,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs
2,OFF-LA-10003223,Office Supplies,Labels,Avery 508
3,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving
4,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...

In [14]:
df['Sub-Category'].unique()

array(['Paper', 'Binders', 'Labels', 'Storage', 'Art', 'Chairs',
       'Fasteners', 'Phones', 'Furnishings', 'Accessories', 'Bookcases',
       'Envelopes', 'Appliances', 'Tables', 'Supplies', 'Machines',
       'Copiers'], dtype=object)

In [15]:
# df[['Ship Mode','Segment','State/Province','Region','Category','Sub-Category']].unique()
# It raises error as unique only works for 1-D data

In [16]:
df[['Category','Ship Mode']].value_counts()

Category         Ship Mode
Office Supplies  Standard Class    3710
Furniture        Standard Class    1314
Office Supplies  Second Class      1174
Technology       Standard Class    1096
Office Supplies  First Class        918
Furniture        Second Class       439
Technology       Second Class       366
Furniture        First Class        329
Office Supplies  Same Day           326
Technology       First Class        301
Furniture        Same Day           119
Technology       Same Day           102
dtype: int64

In [17]:
df['Category'].value_counts()

Office Supplies    6128
Furniture          2201
Technology         1865
Name: Category, dtype: int64

In [18]:
df['Category'].value_counts(normalize=True)*100

Office Supplies    60.113792
Furniture          21.591132
Technology         18.295076
Name: Category, dtype: float64

In [19]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(14)
memory usage: 1.6+ MB

In [21]:
df.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [22]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Returned  800 non-null    object
 1   Order ID  800 non-null    object
dtypes: object(2)
memory usage: 12.6+ KB

In [23]:
managers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Regional Manager  4 non-null      object
 1   Region            4 non-null      object
dtypes: object(2)
memory usage: 192.0+ bytes

In [24]:
df['Sub-Category'].value_counts().sort_values(ascending=True)

Copiers          70
Machines        117
Supplies        192
Fasteners       229
Bookcases       232
Envelopes       256
Tables          326
Labels          368
Appliances      474
Chairs          634
Accessories     775
Art             821
Storage         856
Phones          903
Furnishings    1009
Paper          1384
Binders        1548
Name: Sub-Category, dtype: int64

In [25]:
df.describe()

             Row ID         Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000  10194.000000
mean    5097.500000    228.225854      3.791838      0.155385     28.673417
std     2942.898656    619.906839      2.228317      0.206249    232.465115
min        1.000000      0.444000      1.000000      0.000000  -6599.978000
25%     2549.250000     17.220000      2.000000      0.000000      1.760800
50%     5097.500000     53.910000      3.000000      0.200000      8.690000
75%     7645.750000    209.500000      5.000000      0.200000     29.297925
max    10194.000000  22638.480000     14.000000      0.800000   8399.976000

In [26]:
# selecting all numerical columns
num_cols = df.describe().columns.to_list()
num_cols

['Row ID', 'Sales', 'Quantity', 'Discount', 'Profit']

In [27]:
df[num_cols]

       Row ID    Sales  Quantity  Discount   Profit
0           1   16.448         2       0.2   5.5512
1           2    3.540         2       0.8  -5.4870
2           3   11.784         3       0.2   4.2717
3           4  272.736         3       0.2 -64.7748
4           5   19.536         3       0.2   4.8840
...       ...      ...       ...       ...      ...
10189   10190   52.776         3       0.2  19.7910
10190   10191   20.720         2       0.2   6.4750
10191   10192    3.024         3       0.2  -0.6048
10192   10193   90.930         7       0.0   2.7279
10193   10194    3.024         3       0.2  -0.6048

[10194 rows x 5 columns]

In [28]:
# selecting non numerical columns
non_num_cols = list(set(df.columns)-set(num_cols))
non_num_cols

['Customer ID',
 'City',
 'Country/Region',
 'Order ID',
 'Sub-Category',
 'Segment',
 'Product Name',
 'Ship Date',
 'Postal Code',
 'Category',
 'Region',
 'Customer Name',
 'Order Date',
 'Ship Mode',
 'Product ID',
 'State/Province']

In [29]:
df.select_dtypes(include=['int'])

       Row ID  Quantity
0           1         2
1           2         2
2           3         3
3           4         3
4           5         3
...       ...       ...
10189   10190         3
10190   10191         2
10191   10192         3
10192   10193         7
10193   10194         3

[10194 rows x 2 columns]

In [30]:
df.select_dtypes(include=['int','float'])

       Row ID    Sales  Quantity  Discount   Profit
0           1   16.448         2       0.2   5.5512
1           2    3.540         2       0.8  -5.4870
2           3   11.784         3       0.2   4.2717
3           4  272.736         3       0.2 -64.7748
4           5   19.536         3       0.2   4.8840
...       ...      ...       ...       ...      ...
10189   10190   52.776         3       0.2  19.7910
10190   10191   20.720         2       0.2   6.4750
10191   10192    3.024         3       0.2  -0.6048
10192   10193   90.930         7       0.0   2.7279
10193   10194    3.024         3       0.2  -0.6048

[10194 rows x 5 columns]

In [31]:
df.select_dtypes(exclude=['object'])

       Row ID Order Date  Ship Date    Sales  Quantity  Discount   Profit
0           1 2019-01-03 2019-01-07   16.448         2       0.2   5.5512
1           2 2019-01-04 2019-01-08    3.540         2       0.8  -5.4870
2           3 2019-01-04 2019-01-08   11.784         3       0.2   4.2717
3           4 2019-01-04 2019-01-08  272.736         3       0.2 -64.7748
4           5 2019-01-05 2019-01-12   19.536         3       0.2   4.8840
...       ...        ...        ...      ...       ...       ...      ...
10189   10190 2022-12-30 2023-01-03   52.776         3       0.2  19.7910
10190   10191 2022-12-30 2023-01-03   20.720         2       0.2   6.4750
10191   10192 2022-12-30 2023-01-03    3.024         3       0.2  -0.6048
10192   10193 2022-12-30 2023-01-03   90.930         7       0.0   2.7279
10193   10194 2022-12-30 2023-01-03    3.024         3       0.2  -0.6048

[10194 rows x 7 columns]

In [32]:
#sum of all elements in a column
df.select_dtypes(include=['int']).sum(axis=0) #default value is 0

Row ID      51963915
Quantity       38654
dtype: int64

In [33]:
# sum of all elements in a row
df.select_dtypes(include=['int']).sum(axis=1)

0            3
1            4
2            6
3            7
4            8
         ...
10189    10193
10190    10193
10191    10195
10192    10200
10193    10197
Length: 10194, dtype: int64

Similarly we can find mean, median, count, min, max

In [34]:
#Creating a new column
df['Profit Ratio'] = df['Profit']/df['Sales']
df.select_dtypes(include=['float'])

         Sales  Discount   Profit  Profit Ratio
0       16.448       0.2   5.5512        0.3375
1        3.540       0.8  -5.4870       -1.5500
2       11.784       0.2   4.2717        0.3625
3      272.736       0.2 -64.7748       -0.2375
4       19.536       0.2   4.8840        0.2500
...        ...       ...      ...           ...
10189   52.776       0.2  19.7910        0.3750
10190   20.720       0.2   6.4750        0.3125
10191    3.024       0.2  -0.6048       -0.2000
10192   90.930       0.0   2.7279        0.0300
10193    3.024       0.2  -0.6048       -0.2000

[10194 rows x 4 columns]

In [35]:
df['Profit Ratio'].mean()

0.12221784400156015

In [36]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Profit Ratio'],
      dtype='object')

In [37]:
df['Sales'] = np.round(df['Sales'])
df['Sales']

0         16.0
1          4.0
2         12.0
3        273.0
4         20.0
         ...
10189     53.0
10190     21.0
10191      3.0
10192     91.0
10193      3.0
Name: Sales, Length: 10194, dtype: float64

In [38]:
df['Sales'].astype('int')

0         16
1          4
2         12
3        273
4         20
        ...
10189     53
10190     21
10191      3
10192     91
10193      3
Name: Sales, Length: 10194, dtype: int32

In [39]:
df.set_index(['Row ID'])

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Ratio
Row ID,,,,,,,,,,,,,,,,,,,,,
1,US-2019-103800,2019-01-03,2019-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,...,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.0,2,0.2,5.5512,0.3375
2,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,4.0,2,0.8,-5.4870,-1.5500
3,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,12.0,3,0.2,4.2717,0.3625
4,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,273.0,3,0.2,-64.7748,-0.2375
5,US-2019-141817,2019-01-05,2019-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,...,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,20.0,3,0.2,4.8840,0.2500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10190,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,...,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,53.0,3,0.2,19.7910,0.3750
10191,US-2022-115427,2022-12-30,2023-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,California,...,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,21.0,2,0.2,6.4750,0.3125
10192,US-2022-156720,2022-12-30,2023-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,Colorado,...,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.0,3,0.2,-0.6048,-0.2000
10193,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,...,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,91.0,7,0.0,2.7279,0.0300
10194,CA-2022-143500,2022-12-30,2023-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,Prince Edward Island,...,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.0,3,0.2,-0.6048,-0.2000

In [40]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Ratio
0,1,US-2019-103800,2019-01-03,2019-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.0,2,0.2,5.5512,0.3375
1,2,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,4.0,2,0.8,-5.4870,-1.5500
2,3,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,12.0,3,0.2,4.2717,0.3625
3,4,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,273.0,3,0.2,-64.7748,-0.2375
4,5,US-2019-141817,2019-01-05,2019-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,20.0,3,0.2,4.8840,0.2500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,53.0,3,0.2,19.7910,0.3750
10190,10191,US-2022-115427,2022-12-30,2023-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,21.0,2,0.2,6.4750,0.3125
10191,10192,US-2022-156720,2022-12-30,2023-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.0,3,0.2,-0.6048,-0.2000
10192,10193,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,91.0,7,0.0,2.7279,0.0300
10193,10194,CA-2022-143500,2022-12-30,2023-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.0,3,0.2,-0.6048,-0.2000

In [41]:
#To apply it to df
df.set_index(['Row ID'],inplace=True)
#same can be done with reset_index

In [42]:
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Ratio
Row ID,,,,,,,,,,,,,,,,,,,,,
1,US-2019-103800,2019-01-03,2019-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,...,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.0,2,0.2,5.5512,0.3375
2,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,4.0,2,0.8,-5.4870,-1.5500
3,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,12.0,3,0.2,4.2717,0.3625
4,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,...,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,273.0,3,0.2,-64.7748,-0.2375
5,US-2019-141817,2019-01-05,2019-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,...,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,20.0,3,0.2,4.8840,0.2500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10190,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,...,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,53.0,3,0.2,19.7910,0.3750
10191,US-2022-115427,2022-12-30,2023-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,California,...,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,21.0,2,0.2,6.4750,0.3125
10192,US-2022-156720,2022-12-30,2023-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,Colorado,...,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.0,3,0.2,-0.6048,-0.2000
10193,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,...,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,91.0,7,0.0,2.7279,0.0300
10194,CA-2022-143500,2022-12-30,2023-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,Prince Edward Island,...,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.0,3,0.2,-0.6048,-0.2000

In [43]:
df.reset_index(inplace=True)

In [44]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Ratio
0,1,US-2019-103800,2019-01-03,2019-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.0,2,0.2,5.5512,0.3375
1,2,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,4.0,2,0.8,-5.4870,-1.5500
2,3,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,12.0,3,0.2,4.2717,0.3625
3,4,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,273.0,3,0.2,-64.7748,-0.2375
4,5,US-2019-141817,2019-01-05,2019-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,20.0,3,0.2,4.8840,0.2500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,53.0,3,0.2,19.7910,0.3750
10190,10191,US-2022-115427,2022-12-30,2023-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,21.0,2,0.2,6.4750,0.3125
10191,10192,US-2022-156720,2022-12-30,2023-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.0,3,0.2,-0.6048,-0.2000
10192,10193,US-2022-143259,2022-12-30,2023-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,91.0,7,0.0,2.7279,0.0300
10193,10194,CA-2022-143500,2022-12-30,2023-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.0,3,0.2,-0.6048,-0.2000

In [45]:
df.groupby(['Category']).mean()['Sales']

C:\Users\jaymi\AppData\Local\Temp\ipykernel_15364\2874171425.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['Category']).mean()['Sales']

Category
Furniture          342.908678
Office Supplies    119.445822
Technology         450.380161
Name: Sales, dtype: float64

In [46]:
df.groupby(['Category','Sub-Category']).mean()['Sales']

C:\Users\jaymi\AppData\Local\Temp\ipykernel_15364\2390052147.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['Category','Sub-Category']).mean()['Sales']

Category         Sub-Category
Furniture        Bookcases        497.241379
                 Chairs           529.607256
                 Furnishings       94.736373
                 Tables           638.104294
Office Supplies  Appliances       228.308017
                 Art               33.711328
                 Binders          133.958010
                 Envelopes         64.566406
                 Fasteners         37.262009
                 Labels            34.548913
                 Paper             57.466040
                 Storage          262.455607
                 Supplies         243.390625
Technology       Accessories      216.000000
                 Copiers         2153.528571
                 Machines        1623.316239
                 Phones           367.534884
Name: Sales, dtype: float64

In [48]:
df.groupby(['Region','Segment']).median()['Sales'].unstack()

C:\Users\jaymi\AppData\Local\Temp\ipykernel_15364\983659535.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['Region','Segment']).median()['Sales'].unstack()

Segment  Consumer  Corporate  Home Office
Region
Central      45.5       42.0         51.0
East         51.0       55.0         55.0
South        58.0       49.5         55.5
West         58.0       69.0         55.0

In [49]:
df.groupby(['Region','Segment']).median()['Sales']

C:\Users\jaymi\AppData\Local\Temp\ipykernel_15364\2749846264.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['Region','Segment']).median()['Sales']

Region   Segment
Central  Consumer       45.5
         Corporate      42.0
         Home Office    51.0
East     Consumer       51.0
         Corporate      55.0
         Home Office    55.0
South    Consumer       58.0
         Corporate      49.5
         Home Office    55.5
West     Consumer       58.0
         Corporate      69.0
         Home Office    55.0
Name: Sales, dtype: float64

In [52]:
df.groupby(['Region']).aggregate([np.mean,np.median,np.min,np.max])[['Sales']]

C:\Users\jaymi\AppData\Local\Temp\ipykernel_15364\3699382246.py:1: FutureWarning: ['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Product ID', 'Category', 'Sub-Category', 'Product Name'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.groupby(['Region']).aggregate([np.mean,np.median,np.min,np.max])[['Sales']]

              Sales
               mean median amin     amax
Region
Central  215.495931   46.0  0.0  17500.0
East     231.704287   53.0  1.0  11200.0
South    241.819753   55.0  1.0  22638.0
West     227.440824   61.0  1.0  14000.0

In [54]:
temp = df[df['Profit']>0]

In [55]:
temp['Category'].value_counts()

Office Supplies    5201
Technology         1591
Furniture          1436
Name: Category, dtype: int64

In [56]:
df['Category'].value_counts()

Office Supplies    6128
Furniture          2201
Technology         1865
Name: Category, dtype: int64